### ISSUE TITLE
Array parser fails for array.length === 1 and typeOf string

### ISSUE THREAD

**Issue by richardsawyer** [AlexanderMac/n-params-processor#11]
Error arises here:
https://github.com/AlexanderMac/n-params-processor/blob/9dcfa6f0038ffed73f4ce7bdcb76d963d866d395/src/parsers/array-parser.js#L30

It parses the string to an array of char. Rough fix is:
```
    let val = _.isArray(this.val) ? this.val : [this.val];
    this.val = _.map(val, item => this._parseItem(item));
```

**Comment by AlexanderMac** [comment]
@richardsawyer Could you provide your code, how do you call `parseArray` method?

**Comment by richardsawyer** [comment]
```
        let qb = new MongooseQB({ filter: { site: req.user.currentSite }});
        const allowedCapabilities = ['voice', 'sms', 'mms', 'fax'];
        qb.parseArray({ source: req.query, name: 'capabilities', itemType: 'string', allowed: allowedCapabilities });
```

**Comment by AlexanderMac** [comment]
@richardsawyer I cannot reproduce the bug. Take a look at example below, it doesn't throw any error and works as expected:

```js
const allowedCapabilities = ['voice', 'sms', 'mms', 'fax'];
let source = {
  capabilities: ['voice']
};
let qb = new MongooseQB({
  filter: { site: 'currentSite' }
});
qb.parseArray({ source, name: 'capabilities', itemType: 'string', allowed: allowedCapabilities });

let actual = qb.build();
let expected = {
  fields: '',
  filter: {
    capabilities: [
      'voice'
    ],
    site: 'currentSite'
  },
  pagination: null,
  sorting: null
};

should(actual).eql(expected);
```

**Comment by richardsawyer** [comment]
When express parses the req.query, if there is only one entry for a given field, the field is a string and not an array of string.

e.g. hitting the endpoint
`https://staging.zurili.com/api/communicationRuleSet?type=voice`
results in a res.query of `{type:'voice'}`, not `{type:['voice']}`.

It makes for simpler code to not have to pre-check this before using `.parseArray`. As a workaround I am having to do something like this:
```
req.query.type = _.isArray(req.query.type) ? req.query.type : [req.query.type];
```

**Comment by AlexanderMac** [comment]
You incorrectly send `type` parameter. If you want to send an array with one element, parameter name must be with `[]`: 
```js
{ 'type[]': ['voice'] }
{ 'type[]': ['voice', 'sms'] }
{ 'type': ['voice', 'sms'] }
```

**Comment by richardsawyer** [comment]
You are correct :)

Thank you.
